common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: talle_db
  pool: 5

development: &development
  <<: *common
  host: localhost
  username: root
  password: password
  
production:
  <<: *common  
  host: <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>



